services:
  db:
    image: postgres:14
    restart: always
    container_name: portfolio-dev-db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: ${DATABASE_NAME:-portfolio}
      POSTGRES_USER: ${DATABASE_USER:-postgres}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-postgres}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -h localhost -p 5432 -U ${DATABASE_USER:-postgres}']
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
